// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFZ2lDz-LV5Z38UCy-D2PSU-zd6wGH328',
    appId: '1:216500698195:web:8fbb30deae655265a49aa6',
    messagingSenderId: '216500698195',
    projectId: 'matchwork-9431e',
    authDomain: 'matchwork-9431e.firebaseapp.com',
    storageBucket: 'matchwork-9431e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFnS_cmR0eu-8wkB4U1yqsTigTG-gpqcg',
    appId: '1:216500698195:android:ce379d1439303ba7a49aa6',
    messagingSenderId: '216500698195',
    projectId: 'matchwork-9431e',
    storageBucket: 'matchwork-9431e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmALxxWCz2NnJJJq2i7JVGvg4PC4By0u4',
    appId: '1:216500698195:ios:016548bb52eb43a4a49aa6',
    messagingSenderId: '216500698195',
    projectId: 'matchwork-9431e',
    storageBucket: 'matchwork-9431e.firebasestorage.app',
    iosBundleId: 'com.matchwork.matchworkMobile',
  );
}
