-- ========================================================
-- SCRIPT DE INICIALIZACIÓN DE BASE DE DATOS (SUPABASE)
-- Copia y pega este script en el SQL Editor de tu Dashboard de Supabase
-- ========================================================

-- 1. Crear tabla de perfiles (Profiles)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT,
    role TEXT DEFAULT 'customer',
    avatar_url TEXT,
    profession TEXT,
    category TEXT,
    subcategory TEXT,
    description TEXT,
    price TEXT DEFAULT '$0',
    experience TEXT DEFAULT '5+ años',
    guarantee TEXT DEFAULT '30 días de garantía sobre la mano de obra',
    payment_methods TEXT[] DEFAULT '{"cash", "transfer", "card"}'::text[],
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Crear tabla de disponibilidad de proveedores (Providers)
CREATE TABLE IF NOT EXISTS public.providers (
    id UUID PRIMARY KEY,
    name TEXT NOT NULL,
    image TEXT,
    profession TEXT,
    category TEXT,
    subcategory TEXT,
    rating NUMERIC DEFAULT 4.9,
    status TEXT DEFAULT 'En línea',
    lat NUMERIC,
    lng NUMERIC,
    icon TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Crear tabla de solicitudes de servicio (Service Requests)
CREATE TABLE IF NOT EXISTS public.service_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider_id UUID,
    customer_id UUID,
    message TEXT,
    status TEXT DEFAULT 'pendiente',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Crear tabla de mensajería (Messages)
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id UUID NOT NULL,
    receiver_id UUID NOT NULL,
    text TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Desactivar Row Level Security (RLS) para permitir lectura/escritura libre en el prototipo
ALTER TABLE public.profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.providers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages DISABLE ROW LEVEL SECURITY;



-- 6. Crear tabla para ubicaciones guardadas de usuarios (Fase 2)
CREATE TABLE IF NOT EXISTS public.user_locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    label TEXT NOT NULL, -- Ej: 'Mi Casa', 'Trabajo', 'Playa'
    address TEXT,
    lat NUMERIC NOT NULL,
    lng NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Desactivar Row Level Security (RLS)
ALTER TABLE public.user_locations DISABLE ROW LEVEL SECURITY;

-- 7. Crear tabla para sugerencias y quejas de los usuarios (Fase 2)
CREATE TABLE IF NOT EXISTS public.app_feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    comment TEXT NOT NULL,
    status TEXT DEFAULT 'nuevo',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
-- Desactivar Row Level Security (RLS)
ALTER TABLE public.app_feedback DISABLE ROW LEVEL SECURITY;

-- ========================================================
-- 8. HABILITAR SUPABASE REALTIME
-- ========================================================
-- Esto es crucial para que los mensajes del chat y las alertas
-- de nuevas solicitudes lleguen al instante sin refrescar la página.
begin;
  -- Eliminar la publicación si ya existe para evitar errores
  drop publication if exists supabase_realtime;
  -- Crear la publicación
  create publication supabase_realtime;
commit;

-- Añadir las tablas a la publicación de realtime
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.service_requests;
